service: classifier
runtime: python39
env: standard

instance_class: F4_1G

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  min_idle_instances: automatic
  max_idle_instances: automatic

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 10

service_account: huze-management@appspot.gserviceaccount.com
